version: "3.8"

services:
    postgres:
        image: postgres:16
        container_name: langgraph-postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: testdb
        ports:
            - "5434:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
